name: Generate MIOPEN database

on:
  workflow_call:
    inputs:
      rocm_release:
        type: string
        description: ROCm release version
        required: true
        default: "5.1"
      miopen_db_repo:
        type: string
        description: MIOpen Database repository
        default: "migraphx-benchmark/miopen-databases"
        required: false
      script_repo:
        type: string
        description: Script repository (rocm-migraphx)
        default: "migraphx-benchmark/rocm-migraphx"
        required: false
      saved_models_path:
        type: string
        description: Saved Models path
        default: "/home/htec/jz/source/saved-models"
        required: false
      test_results_dir:
        type: string
        description: Test results path
        default: "/home/htec/jz/source/rocm-migraphx/test-results"
        required: false
    secrets:
      gh_token:
        description: 'Github Access Token'
        required: true

env:
  ROCM_VERSION: rocm-${{ inputs.rocm_release }}
  MIOPEN_PATH: miopen-databases
  SCRIPT_PATH: rocm-migraphx

jobs:
  check_gpu_name:
    name: Check GPU name
    runs-on: self-hosted
    outputs:
      gpu_name: ${{ steps.gpu.outputs.gpu_name }}
    steps:
      - name: Check GPU info
        id: gpu
        run: |
          GPU_NAME="$(lshw -C display | awk -F'product: ' '/product/{print $2}' | awk -F '\[|\]' '{print $2}')"
          GPU_NAME=${GPU_NAME//$'\n'/}
          GPU_NAME=${GPU_NAME// /_}
          echo "::set-output name=gpu_name::$GPU_NAME"
  check_image_version:
    name: Check Image Version
    runs-on: self-hosted
    needs: check_gpu_name
    outputs:
      image: ${{ steps.check_image.outputs.image }}
    steps:
      - name: Check new image
        id: check_image
        run: |
          if [ ! -z "$(docker images -q rocm-migraphx:${{ inputs.rocm_release }})" ]; then
            echo "::set-output name=image::true"
          fi
  check_database:
    name: Check database path
    runs-on: self-hosted
    needs: check_gpu_name
    outputs:
      database: ${{ steps.check_database.outputs.database }}
    steps:
      - name: Checkout scripts
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.miopen_db_repo }}
          path: ${{ env.MIOPEN_PATH }}
          token: ${{ secrets.gh_token }}

      - name: Check Database path
        id: check_database
        run: |
          if [ ! -d "$GITHUB_WORKSPACE/${{ env.MIOPEN_PATH }}/${{ env.ROCM_VERSION }}/${{ needs.check_gpu_name.outputs.gpu_name }}" ]; then
            echo "::set-output name=database::true"
          fi
  create_database:
    name: Create MIOPEN Database
    runs-on: self-hosted
    needs: [check_image_version, check_database]
    if: ( needs.check_database.outputs.database == 'true' && needs.check_image_version.outputs.image == 'true' )
    steps:
      - name: Checkout scripts
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.miopen_db_repo }}
          path: ${{ env.SCRIPT_PATH}}
          token: ${{ secrets.gh_token }}
      - name: Perform tuning database
        run: >
          docker run -e TZ=America/Chicago
          -e TARGET=gpu
          -e SAVED_MODELS=/data
          -e TEST_RESULTDIR=/results
          -e MIOPEN_FIND_ENFORCE=search
          --device=/dev/dri
          --device=/dev/kfd
          --network=host
          --group-add=video 
          -v ${{ inputs.saved_models_path }}:/data
          -v ${{ inputs.test_results_dir }}:/results
          --workdir /src/${{ env.SCRIPT_PATH }}/scripts/
          rocm-migraphx:${{ inputs.rocm_release }} /bin/bash -c "./run_perf_mev.sh; cp -r /root/.config/miopen /data/database"
  push_database:
    name: Push MIOPEN Database
    runs-on: self-hosted
    needs: [create_database, check_gpu_name]
    steps:
      - name: Checkout scripts
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.miopen_db_repo }}
          path: ${{ env.MIOPEN_PATH }}
          token: ${{ secrets.gh_token }}

      - name: Push database to git
        run: |
          cd $GITHUB_WORKSPACE/${{ env.MIOPEN_PATH }}/
          mkdir -p ${{env.ROCM_VERSION}}/${{ needs.check_gpu_name.outputs.gpu_name }}
          cp -r /home/htec/jz/database/* ${{env.ROCM_VERSION}}/${{ needs.check_gpu_name.outputs.gpu_name }}
          git add .
          git config --local user.email github-actions
          git config --local user.name github-actions@github.com
          git commit -m "Push databases" -a
          git push
