name: MIGraphX Performance Tests dummy

on:
  workflow_call:
    inputs:
      rocm_release:
        type: string
        description: ROCm release version
        required: true
      performance_reports_repo:
        type: string
        description: Result repository
        required: true
      benchmark_utils_repo:
        type: string
        description: Repository where benchmark utils are stored
        required: true
      organization:
        type: string
        description: Organization based on which location of files will be different
        required: true
#      migraphx_path:
#        type: string
#        description: Main migraphx directory
#        required: true
#      test_results_path:
#        type: string
#        description: Path to test results
#        required: true
#      reports_path:
#        type: string
#        description: Path to reports
#        required: true
      result_number:
        type: string
        description: Number of last results
        required: true
      flags:
        type: string
        description: -m for Max value; -s for Std dev; -r 'path' for Threshold file
        required: true
    secrets:
      gh_token:
        description: 'Github Access Token'
        required: true
      mail_user:
        description: 'Email username'
        required: true
      mail_pass:
        description: 'Email password'
        required: true

env:
  UTILS_DIR: benchmark-utils
  REPORTS_DIR: migraphx-reports
  DOCKERBASE: rocm-migraphx:${{ inputs.rocm_release }}
  MIOPENTUNE: miopen-dbs/rocm${{ inputs.rocm_release }}
  MAIL_TO: dl.dl-migraphx-perfrun@amd.com
  MAIL_CC: igor.mirosavljevic@htecgroup.com,djordje.petrovic@htecgroup.com,milos.miljanovic@htecgroup.com,pavle.jacovic@htecgroup.com
  MAIL_FROM: GH Actions
  MAIL_SUBJECT: Nightly Performance run
  MAIL_BODY: Scheduled Performance test run on develop branch
  PR_ID: ${{ github.event.number }}
  BRANCH_NAME: ${{ github.base_ref }}
  REPORTS_PATH: /usr/share/migraphx/"${{ inputs.organization }}/reports
  TEST_RESULTS_PATH: /usr/share/migraphx/${{ inputs.organization }}/test-results
  MIGRAPHX_PATH: /usr/share/migraphx/${{ inputs.organization }}

jobs:
  performance_test:
    name: MIGraphX Performance
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip bot checks') }}
    runs-on: self-hosted
    outputs:
      git_sha: ${{ steps.git_sha.outputs.git_sha }}
    steps:
      - name: Update PR env
        if: ${{ github.event_name == 'pull_request'}}
        run: |
          echo "BRANCH_NAME=${{ github.head_ref }}" >> $GITHUB_ENV
          echo "TEST_RESULTS_PATH=$(echo "$TEST_RESULTS_PATH-$PR_ID")" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Checkout utils
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.benchmark_utils_repo }}
          path: ${{ env.UTILS_DIR }}
          token: ${{ secrets.gh_token }}

      - name: Get git SHA
        id: git_sha
        run: |
          cd $GITHUB_WORKSPACE
          SHA=$(git log | head -1 | awk '{print $2}' | cut -c 1-6)
          echo "git_sha=$SHA" >> $GITHUB_OUTPUT

      - name: Docker build
        if: ${{ github.event.action != 'closed' }}
        run: >
          cd $GITHUB_WORKSPACE/${{ env.UTILS_DIR }} && docker build --no-cache
          --build-arg BRANCH=${{ env.BRANCH_NAME }} 
          --build-arg DOCKERBASE=${{ env.DOCKERBASE }}
          --build-arg MIOPENTUNE=${{ env.MIOPENTUNE }}
          -t "migraphx-rocm:${{ inputs.rocm_release }}-${{ steps.git_sha.outputs.git_sha }}" 
          -f dockerfiles/Daily.Dockerfile .

      - name: Run performance tests
        if: ${{ github.event.action != 'closed' }}
        run: >
          docker run -e TZ=America/Chicago
          -e TARGET=gpu
          -e PYTHONPATH=/src/AMDMIGraphX/build/lib
          --device=/dev/dri
          --device=/dev/kfd
          --network=host
          --group-add=video
          -v /usr/share/migraphx/saved-models:/saved-models:ro
          -v /usr/share/migraphx/new-saved-models:/new-saved-models:ro
          -v $GITHUB_WORKSPACE/${{ env.UTILS_DIR }}/scripts:/migraphx/sh:ro
          -v ${{ env.TEST_RESULTS_PATH }}:/data/test-results
          --workdir /migraphx/sh
          migraphx-rocm:${{ inputs.rocm_release }}-${{ steps.git_sha.outputs.git_sha }} /bin/bash performance_tests2.sh

      - name: Delete old images/containers
        if: ${{ github.event_name == 'schedule' }}
        run: |
          docker container prune -f
          if [[ $(docker images --filter=reference="migraphx-rocm:${{ inputs.rocm_release }}-*" | awk 'NR>1 {print $3}') ]]; then
            docker rmi -f $(docker images --filter=reference="migraphx-rocm:${{ inputs.rocm_release }}-*" | awk 'NR>1 {print $3}')
          fi
          docker image prune -f

      - name: Checkout report's repo
        if: ${{ github.event_name == 'schedule' }}
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.performance_reports_repo }}
          path: ${{ env.REPORTS_DIR }}
          token: ${{ secrets.gh_token }}

      - name: Execute report script
        if: ${{ github.event_name == 'schedule' }}
        run: |
          python3 $GITHUB_WORKSPACE/${{ env.UTILS_DIR }}/scripts/report.py \
          -t '${{ env.TEST_RESULTS_PATH }}' \
          -r '${{ env.REPORTS_PATH }}'
          python3 $GITHUB_WORKSPACE/${{ env.UTILS_DIR }}/scripts/history.py -n \
          -t '${{ env.TEST_RESULTS_PATH }}' \
          -r '${{ env.REPORTS_PATH }}'
          cp -r ${{ env.REPORTS_PATH }}/results-* $GITHUB_WORKSPACE/${{ env.REPORTS_DIR }}/
          cd $GITHUB_WORKSPACE/${{ env.REPORTS_DIR }}/
          git add .
          git config --local user.email github-actions
          git config --local user.name github-actions@github.com
          git commit -m "Push report" -a
          git push

      - name: Execute comment script
        id: auto_comment
        if: ${{ github.event_name != 'schedule' && github.event_name == 'pull_request' && github.event.action != 'closed'}}
        run: |
          if [ ${{ inputs.flags }} == "-r" ]; then
            flagoptions="${{ inputs.flags }} $GITHUB_WORKSPACE/${{ env.UTILS_DIR }}/scripts/"
          else
            flagoptions="${{ inputs.flags }}"
          fi 
          python3 $GITHUB_WORKSPACE/${{ env.UTILS_DIR }}/scripts/comment.py -t ${TEST_RESULTS_PATH//-$PR_ID/} -n ${{ inputs.result_number }} $flagoptions -p

      - name: Create a comment on PR
        if: ${{ github.event_name != 'schedule' && github.event_name == 'pull_request' && github.event.action != 'closed'}}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: performance
          GITHUB_TOKEN: ${{ secrets.gh_token }}
          path: ${{ github.workspace }}/${{ env.UTILS_DIR }}/scripts/temp.md

      - name: Get latest accuracy results
        id: accuracy
        if: ${{ github.event.action != 'closed' }}
        run: |
          cd ${{ env.TEST_RESULTS_PATH }}
          ACCURACY=$(ls -dt accuracy* | head -1)
          echo "last_test=$ACCURACY" >> $GITHUB_OUTPUT

      - name: Create accuracy comment on PR
        if: ${{ github.event_name != 'schedule' && github.event_name == 'pull_request' && github.event.action != 'closed'}}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: accuracy
          GITHUB_TOKEN: ${{ secrets.gh_token }}
          path: ${{ env.TEST_RESULTS_PATH }}/${{ steps.accuracy.outputs.last_test }}/results.md

      - name: Get latest report
        id: last_report
        if: ${{ github.event_name == 'schedule' }}
        run: |
          cd ${{ env.REPORTS_PATH }}
          latest="$(readlink -f $(ls -tp | grep -v /$ | head -1))"
          echo "latest=$latest" >> $GITHUB_OUTPUT

      - name: Send mail
        if: ${{ github.event_name == 'schedule' }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.mail_user }}
          password: ${{ secrets.mail_pass }}
          subject: ${{ env.MAIL_SUBJECT }}
          to: ${{ env.MAIL_TO }}
          from: ${{ env.MAIL_FROM }}
          secure: true
          body: ${{ env.MAIL_BODY }}
          cc: ${{ env.MAIL_CC }}
          ignore_cert: true
          attachments: ${{ steps.last_report.outputs.latest}}
          priority: normal

      - name: Clean merged PR data
        if: ${{ github.event.action == 'closed' && github.event.pull_request.merged == true}}
        run: >
          docker run
          -v $GITHUB_WORKSPACE/${{ env.UTILS_DIR }}/scripts:/migraphx/sh:ro
          -v ${{ env.MIGRAPHX_PATH }}:/data/migraphx
          --workdir /migraphx/sh
          rocm-migraphx:${{ inputs.rocm_release }} bash -c "./clean_after_pr.sh ${{ env.TEST_RESULTS_PATH }} ${{ env.PR_ID }} merged"

      - name: Clean closed PR data
        if: ${{ github.event.action == 'closed' && github.event.pull_request.merged == false}}
        run: >
          docker run
          -v $GITHUB_WORKSPACE/${{ env.UTILS_DIR }}/scripts:/migraphx/sh:ro
          -v ${{ env.MIGRAPHX_PATH }}:/data/migraphx
          --workdir /migraphx/sh
          rocm-migraphx:${{ inputs.rocm_release }} bash -c "./clean_after_pr.sh ${{ env.TEST_RESULTS_PATH }} ${{ env.PR_ID }} closed"
